import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import AxeBuilder from '@axe-core/playwright';

test.beforeEach(async({context,page})=>{
  await context.addCookies([{name:'__sites_local_auth',value:'1',url:'http://localhost:6173'}]);
  await page.request.post('http://127.0.0.1:6199/__control',{data:{failDiscovery:0,changedLicense:false,failNature:0,failChat:0,failSubmit:0,failSave:0,largeNature:false,delay:300}});
  const jpeg=await readFile('public/images/sample-rv.jpg');
  await page.route('https://thumb.wikimedia.org/**',route=>route.fulfill({contentType:'image/jpeg',body:jpeg}));
});

test('A detailed misspelled search broadens transparently and paginates the working query',async({page})=>{
  await page.goto('/?view=library&kind=landscape');
  await page.getByRole('button',{name:'Find real photos',exact:true}).click();
  await page.getByLabel('Place or scenery').fill('burning man concenrt open area');
  await page.getByLabel('Original resolution').selectOption('4k');
  await page.getByRole('button',{name:'Search photos',exact:true}).click();
  await expect(page.locator('.discovery-card')).toHaveCount(2);
  await expect(page.getByText('Broadened your search to “burning man”. Your 4K+ resolution and public-domain/CC0 filters are unchanged.',{exact:true})).toBeVisible();
  await expect(page.getByLabel('Place or scenery')).toHaveValue('burning man concenrt open area');
  await page.getByRole('button',{name:'Find more photos',exact:true}).click();
  await expect(page.locator('.discovery-card')).toHaveCount(4);
  const log=await(await page.request.get('http://127.0.0.1:6199/__control')).json();
  const requests=log.records.filter((r:any)=>r.kind==='discovery'&&r.query?.includes('burning'));
  expect(requests.at(-1).query).toContain('"burning man"');
  expect(requests.at(-1).query).not.toContain('concert');
  expect(requests.every((r:any)=>!r.query.includes('hastemplate:'))).toBe(true);
  expect(requests.every((r:any)=>r.query.includes('filew:>3839'))).toBe(true);
});

test('Search, review, failed import recovery, duplicate protection and reload',async({page},info)=>{
  const index=['desktop-light','mobile-light','desktop-dark'].indexOf(info.project.name)+1;
  await page.goto('/?view=library&kind=landscape');
  await page.getByRole('button',{name:'Find real photos',exact:true}).click();
  await page.getByLabel('Place or scenery').fill('Alaska case'+index);
  await page.request.post('http://127.0.0.1:6199/__control',{data:{failDiscovery:1}});
  await page.getByRole('button',{name:'Search photos',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('temporarily unavailable');
  await expect(page.getByLabel('Place or scenery')).toHaveValue('Alaska case'+index);
  await page.getByRole('button',{name:'Retry search',exact:true}).click();
  await expect(page.locator('.discovery-card')).toHaveCount(1);
  await page.getByRole('button',{name:'Find more photos',exact:true}).click();
  await expect(page.locator('.discovery-card')).toHaveCount(2);
  await page.getByLabel('Original resolution').selectOption('4k');
  await page.getByRole('button',{name:'Search photos',exact:true}).click();
  await expect(page.locator('.discovery-card')).toHaveCount(2);
  await page.screenshot({path:info.outputPath('landscape-search.png'),fullPage:false});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBe(true);
  const violations=(await new AxeBuilder({page}).include('.landscape-discovery').analyze()).violations;
  expect(violations).toEqual([]);
  await page.getByRole('button',{name:'Review photo',exact:true}).first().click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('link',{name:'Source & photographer'})).toHaveAttribute('href',new RegExp('commons.wikimedia.org'));
  await page.getByLabel('Library name').fill('Reviewed Alaska '+index);
  await page.getByLabel('Scenery',{exact:true}).selectOption('meadow');
  await page.getByLabel('Ground space',{exact:true}).selectOption('placement');
  await page.getByLabel('Placement notes',{exact:false}).fill('Level foreground on the left.');
  await page.screenshot({path:info.outputPath('landscape-review.png'),fullPage:false});
  expect((await new AxeBuilder({page}).include('[role="dialog"]').analyze()).violations).toEqual([]);
  await page.request.post('http://127.0.0.1:6199/__control',{data:{failNature:1}});
  await page.getByRole('button',{name:'Add to library',exact:true}).click();
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('could not be prepared');
  await expect(page.getByLabel('Library name')).toHaveValue('Reviewed Alaska '+index);
  await page.getByRole('button',{name:'Add to library',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByText('“Reviewed Alaska '+index+'” is in your photo library.',{exact:true})).toBeVisible();
  const request={pageId:900000+index*100,name:'Duplicate should not replace',environment:'other',suitability:'scenery'};
  const repeat=await page.request.post('/api/studio/landscape-import',{data:request});
  expect(repeat.ok()).toBe(true);const asset=await repeat.json();expect(asset.name).toBe('Reviewed Alaska '+index);
  expect(asset.photo_source.placementNote).toBe('Level foreground on the left.');
  await page.getByRole('button',{name:'View library',exact:true}).click();
  await page.getByRole('textbox',{name:'Search library'}).fill(asset.name);
  await expect(page.getByRole('img',{name:asset.name,exact:true})).toHaveCount(1);
  await page.reload();
  await page.getByRole('textbox',{name:'Search library'}).fill(asset.name);
  await expect(page.getByRole('img',{name:asset.name,exact:true})).toHaveCount(1);
  const state=await (await page.request.get('/api/studio/state')).json();
  expect(state.assets.filter((a:any)=>a.id===asset.id)).toHaveLength(1);
});

test('Add and use a reviewed backdrop in composition; reject changed rights and URL injection',async({page},info)=>{
  const index=['desktop-light','mobile-light','desktop-dark'].indexOf(info.project.name)+11;
  await page.goto('/');await expect(page.getByRole('navigation')).toBeVisible();
  const p=await(await page.request.post('/api/studio/projects',{data:{name:'Discovery journey '+index}})).json();
  await page.goto('/?project='+p.id);
  await page.getByRole('button',{name:'Select Travel trailer · sample',exact:true}).click();
  await page.getByRole('button',{name:'Choose the setting',exact:true}).click();
  await page.getByRole('tab',{name:'Find real photos',exact:true}).click();
  await page.getByLabel('Place or scenery').fill('Alaska case'+index);
  await page.getByRole('button',{name:'Search photos',exact:true}).click();
  await page.getByRole('button',{name:'Review photo',exact:true}).first().click();
  await page.getByLabel('Library name').fill('Journey backdrop '+index);
  await page.request.post('http://127.0.0.1:6199/__control',{data:{changedLicense:true}});
  await page.getByRole('button',{name:'Add & use backdrop',exact:true}).click();
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('no longer meets');
  await page.request.post('http://127.0.0.1:6199/__control',{data:{changedLicense:false}});
  await page.getByRole('button',{name:'Add & use backdrop',exact:true}).click();
  await expect(page.getByRole('button',{name:'Generate 4 takes',exact:true})).toBeVisible();
  await expect(page.getByText('Real-photo backdrop',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Generate 4 takes',exact:true}).click();
  await expect(page.getByText('4 of 4 ready',{exact:true})).toBeVisible({timeout:30000});
  const bad=await page.request.post('/api/studio/landscape-import',{data:{pageId:12,name:'bad',environment:'meadow',suitability:'placement',originalUrl:'http://127.0.0.1/private'}});
  expect(bad.status()).toBe(400);
  expect((await page.request.get('/api/studio/landscape-search?query=x&offset=-1')).status()).toBe(400);
  await page.getByRole('navigation').getByRole('button',{name:'Library',exact:true}).click();
  await page.getByRole('tab',{name:'Landscapes',exact:true}).click();
  await page.getByRole('button',{name:'Find real photos',exact:true}).click();
  await page.getByLabel('Place or scenery').fill('nomatchingbackdrop');
  await page.getByRole('button',{name:'Search photos',exact:true}).click();
  await expect(page.getByText('No eligible photos in these results.',{exact:true})).toBeVisible();
});
