import test from 'node:test';
import assert from 'node:assert/strict';
import {buildPrompt,modelFor,providerInput,requestSchema,activeStatus} from '../lib/domain.ts';
test('All Sunburst operations explicitly request Max and one image per independent job',()=>{for(const stage of ['landscape','compose','objects','prop'] as const){const input=providerInput(stage,'brief','landscape_4_3',['rv','landscape']);assert.equal(input.quality,'max');assert.equal(input.num_images,1);assert.ok(modelFor(stage).includes('sunburst'));}});
test('People uses Meta Muse, only selected base inputs, and no unsupported Max parameter',()=>{const input=providerInput('people','brief','landscape_4_3',['selected-scene']);assert.equal(modelFor('people'),'meta/muse-image/edit');assert.deepEqual(input.image_urls,['selected-scene']);assert.ok(!('quality' in input));});
test('Only edit stages receive reference images',()=>{for(const stage of ['landscape','prop'] as const)assert.ok(!('image_urls' in providerInput(stage,'brief','square_hd',['ignored'])));assert.deepEqual(providerInput('compose','brief','landscape_4_3',['rv','landscape']).image_urls,['rv','landscape']);});
test('Photographic prompts isolate generation stages and keep variant direction distinct',()=>{const prompts=[0,1,2,3].map(slot=>buildPrompt('compose','Preserve my RV.',slot));assert.equal(new Set(prompts).size,4);assert.ok(prompts.every(p=>p.includes('No people or added props')&&p.includes('Preserve my RV.')));assert.match(buildPrompt('landscape','Alpine lake',0),/No RVs, vehicles, people/);});
test('Request validation blocks unsupported routing and invalid request identifiers',()=>{const valid={id:crypto.randomUUID(),project_id:'project',stage:'compose',prompt:'A photographic RV composition'};assert.ok(requestSchema.safeParse(valid).success);assert.ok(!requestSchema.safeParse({...valid,stage:'arbitrary-model'}).success);assert.ok(!requestSchema.safeParse({...valid,id:'not-an-id'}).success);assert.ok(!requestSchema.safeParse({...valid,prompt:'x'}).success);});
test('Only actionable job states continue polling',()=>{for(const s of ['queued','submitting','generating','saving'])assert.equal(activeStatus(s),true);for(const s of ['ready','failed','unknown','save_failed'])assert.equal(activeStatus(s),false);});
