export interface NaturePhoto {
  previewUrl?: string;
  pageId?: number;
  importedAt?: number;
  id: string;
  name: string;
  location: string;
  environment: string;
  lighting: string;
  width: number;
  height: number;
  originalUrl: string;
  sourceUrl: string;
  photographer: string;
  license: string;
  licenseUrl: string;
  placementNote: string;
  mime: string;
  suitability: "placement" | "scenery";
}

// Curated, verified originals. Never populate this catalog from user URLs.
export const naturePhotos: NaturePhoto[] = [
  {
    "id": "commons-162447820",
    "name": "Margarita Lookout Dirt Road",
    "location": "Margarita Lookout Road, California, USA",
    "environment": "road",
    "lighting": "daylight",
    "width": 8064,
    "height": 6048,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Margarita_Peak_from_Margarita_Lookout_Road_%288S01%29_1_of_2.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Margarita_Peak_from_Margarita_Lookout_Road_(8S01)_1_of_2.jpg",
    "photographer": "Z3lvs",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Broad pale dirt road in the foreground, green mountain backdrop and open sky. Match road perspective and the daylight shadow direction.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-142713099",
    "name": "Lone Pine Sierra Road",
    "location": "Near Lone Pine, California, USA",
    "environment": "road",
    "lighting": "daylight",
    "width": 8064,
    "height": 6048,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/9/94/Sierra_Nevada_Mountains_Near_Lone_Pine%2C_California_04_30_2022.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sierra_Nevada_Mountains_Near_Lone_Pine,_California_04_30_2022.jpg",
    "photographer": "Z3lvs",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Wide paved road and gravel shoulder with distant snowy Sierra peaks. Strong vanishing point provides a clear vehicle ground plane.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-185149202",
    "name": "Humbug Mountain Woodland Clearing",
    "location": "Humbug Mountain State Park, Oregon, USA",
    "environment": "forest",
    "lighting": "diffuse daylight",
    "width": 8064,
    "height": 6048,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/7/79/Under_the_California_Bay_Laurel_Trees_-_Humbug_Mountain_State_Park%2C_Oregon_1.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Under_the_California_Bay_Laurel_Trees_-_Humbug_Mountain_State_Park,_Oregon_1.jpg",
    "photographer": "Z3lvs",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Leaf-covered foreground clearing beneath low woodland branches. Best for a small camper at restrained scale; check branch clearance and ground slope.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-163905158",
    "name": "Bachelor Mountain Spring Meadow",
    "location": "Riverside County, California, USA",
    "environment": "meadow",
    "lighting": "daylight",
    "width": 8064,
    "height": 6048,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/9/91/Bachelor_Mountain%2C_Riverside_County%2C_California.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bachelor_Mountain,_Riverside_County,_California.jpg",
    "photographer": "Z3lvs",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Broad low grass and level land in front of a mountain. Keep vehicle below the mountain skyline and match bright overhead light.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-147295203",
    "name": "Idyllwild Mountain Turnout",
    "location": "Highway 74 near Idyllwild, California, USA",
    "environment": "road",
    "lighting": "daylight",
    "width": 8064,
    "height": 6048,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Hwy_74_Turnout_on_the_way_to_Idyllwild%2C_California.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hwy_74_Turnout_on_the_way_to_Idyllwild,_California.jpg",
    "photographer": "Z3lvs",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Visible paved turnout at the bottom edge with a valley beyond. Place tires within the paved foreground; limited depth calls for a close vehicle crop.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-148252882",
    "name": "Alaska Grassy Pass Plain",
    "location": "Grassy Pass, Denali National Park and Preserve, Alaska, USA",
    "environment": "mountain",
    "lighting": "daylight",
    "width": 9331,
    "height": 5635,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e2/The_view_from_Grassy_Pass_%282ec30051-1dd8-b71c-0720-b34020aab069%29.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:The_view_from_Grassy_Pass_(2ec30051-1dd8-b71c-0720-b34020aab069).jpg",
    "photographer": "Jacob W. Frank",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:The_view_from_Grassy_Pass_(2ec30051-1dd8-b71c-0720-b34020aab069).jpg",
    "placementNote": "Broad gravel plain beneath the Alaska Range. Use dry gravel ground and avoid the narrow water channels; match the distant mountain scale.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-163447633",
    "name": "Whitewater Mountain Road",
    "location": "Cottonwood Road, Whitewater, California, USA",
    "environment": "road",
    "lighting": "daylight",
    "width": 8064,
    "height": 6048,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Whitewater%2C_California_-_Cottonwood_Road.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Whitewater,_California_-_Cottonwood_Road.jpg",
    "photographer": "Z3lvs",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Wide quiet paved road with mountain backdrop; utility poles and low buildings are present in the middle distance.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-112854724",
    "name": "Monument Valley Haze",
    "location": "Monument Valley, Arizona, USA",
    "environment": "desert",
    "lighting": "golden hour",
    "width": 8322,
    "height": 4682,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f7/Fog_Valley_%2819489500310%29.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fog_Valley_(19489500310).jpg",
    "photographer": "Romain Guy",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Flat distant desert foreground with ample negative space; haze requires softened contrast on the vehicle.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-112854716",
    "name": "Monument Valley Afterglow",
    "location": "Monument Valley, Arizona, USA",
    "environment": "desert",
    "lighting": "sunset",
    "width": 8657,
    "height": 4871,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f3/Gradient_Valley_%2819661314198%29.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gradient_Valley_(19661314198).jpg",
    "photographer": "Romain Guy",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Open red earth beneath distant buttes; use the central flat area and avoid sloping rock at lower left.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-112854698",
    "name": "Monument Valley Storm",
    "location": "Navajo County, Arizona, USA",
    "environment": "desert",
    "lighting": "storm light",
    "width": 8688,
    "height": 4888,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/7/7e/Into_the_Storm_%2832450652070%29.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Into_the_Storm_(32450652070).jpg",
    "photographer": "Romain Guy",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Broad open sandy foreground gives clear vehicle space under a dramatic storm sky.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-112854722",
    "name": "Monument Valley Three Buttes",
    "location": "Monument Valley, Arizona, USA",
    "environment": "desert",
    "lighting": "storm light",
    "width": 8491,
    "height": 4777,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/1/17/West_Mitten_Butte%2C_East_Mitten_Butte%2C_and_Merrick_Butte_%2819090208003%29.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:West_Mitten_Butte,_East_Mitten_Butte,_and_Merrick_Butte_(19090208003).jpg",
    "photographer": "Romain Guy",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Expansive red-earth foreground with distant buttes and clear sky separation.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-105710167",
    "name": "Yosemite Winter Clearing",
    "location": "Yosemite National Park, California, USA",
    "environment": "snow",
    "lighting": "daylight",
    "width": 7896,
    "height": 5235,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/5/5e/Snow_covering_Yosemite_National_Park._%2876592e78381c4b8ba1c9ea5447f3f3d2%29.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Snow_covering_Yosemite_National_Park._(76592e78381c4b8ba1c9ea5447f3f3d2).jpg",
    "photographer": "Milo Woodbridge Williams",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Snow_covering_Yosemite_National_Park._(76592e78381c4b8ba1c9ea5447f3f3d2).jpg",
    "placementNote": "Wide snow-covered clearing with distant trees; suitable for a winter scene with snow contact shadows. Archival color photograph.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-88092692",
    "name": "Hayden Valley Winter",
    "location": "Yellowstone National Park, Wyoming, USA",
    "environment": "snow",
    "lighting": "overcast",
    "width": 8688,
    "height": 5792,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/5/52/Black_tree_and_white_landscape_in_Hayden_Valley_%2826372572628%29.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Black_tree_and_white_landscape_in_Hayden_Valley_(26372572628).jpg",
    "photographer": "Jacob W. Frank / NPS",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Black_tree_and_white_landscape_in_Hayden_Valley_(26372572628).jpg",
    "placementNote": "Open rolling snow foreground and a solitary tree; preserve subdued winter contrast.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-117050504",
    "name": "Malchin Open Hay Meadow",
    "location": "Malchin, Mecklenburg-Vorpommern, Germany",
    "environment": "meadow",
    "lighting": "daylight",
    "width": 8368,
    "height": 5584,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/d/de/Meadow_in_Malchin_2021-09-08_12.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meadow_in_Malchin_2021-09-08_12.jpg",
    "photographer": "Leonhard Lenz",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Open low grass with hay bales spaced in the distance and a tree-line backdrop. Broad level foreground supports clear wheel contact.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-117416602",
    "name": "Zirkow Grass Tracks",
    "location": "Zirkow, Rügen, Germany",
    "environment": "meadow",
    "lighting": "daylight",
    "width": 8368,
    "height": 5584,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/5/57/Meadow_in_Zirkow_2021-09-12_08.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meadow_in_Zirkow_2021-09-12_08.jpg",
    "photographer": "Leonhard Lenz",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Wide green foreground crossed by faint farm tracks; distant trees give a simple horizon. Match low angled daylight.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-116995325",
    "name": "Basedow Woodland Meadow",
    "location": "Basedow, Mecklenburg-Vorpommern, Germany",
    "environment": "meadow",
    "lighting": "daylight",
    "width": 8368,
    "height": 5584,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/1/14/Meadow_in_Basedow_2021-09-07_09.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meadow_in_Basedow_2021-09-07_09.jpg",
    "photographer": "Leonhard Lenz",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Flattened grass tracks lead across an open meadow beside trees. Place on the tracks and match the vegetation height around tires.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-128219639",
    "name": "Niederfinow Meadow Path",
    "location": "Niederfinow, Brandenburg, Germany",
    "environment": "meadow",
    "lighting": "daylight",
    "width": 8384,
    "height": 5612,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/b/bb/Meadow_in_Niederfinow_2021-07-17_01.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meadow_in_Niederfinow_2021-07-17_01.jpg",
    "photographer": "Leonhard Lenz",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "A mown green track runs between an open meadow and taller grass under cumulus clouds. Center the vehicle on the track.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-128219803",
    "name": "Niederfinow Dirt Lane",
    "location": "Niederfinow, Brandenburg, Germany",
    "environment": "road",
    "lighting": "daylight",
    "width": 8384,
    "height": 5612,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/b/bf/Meadow_in_Niederfinow_2021-07-17_17.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meadow_in_Niederfinow_2021-07-17_17.jpg",
    "photographer": "Leonhard Lenz",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Clear dirt lane and broad grassy verge in the foreground. Strong lane perspective helps place a motorhome or trailer.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-128219932",
    "name": "Niederfinow Cloud Meadow",
    "location": "Niederfinow, Brandenburg, Germany",
    "environment": "meadow",
    "lighting": "daylight",
    "width": 8384,
    "height": 5612,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/6/61/Meadow_in_Niederfinow_2021-07-17_30.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meadow_in_Niederfinow_2021-07-17_30.jpg",
    "photographer": "Leonhard Lenz",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Broad open grassy foreground and a low distant tree horizon beneath sculpted clouds. Preserve natural grass contact around tires.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-117158021",
    "name": "Verchen Forest Edge",
    "location": "Verchen, Mecklenburg-Vorpommern, Germany",
    "environment": "meadow",
    "lighting": "daylight",
    "width": 8368,
    "height": 5584,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b1/Meadow_in_Verchen_2021-09-09_07.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meadow_in_Verchen_2021-09-09_07.jpg",
    "photographer": "Leonhard Lenz",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Open field bordered by a dark tree line at left. Ground is gently sloping; match the slope and low side light.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-117416680",
    "name": "Zirkow Tall Grass Clearing",
    "location": "Zirkow, Rügen, Germany",
    "environment": "meadow",
    "lighting": "daylight",
    "width": 8368,
    "height": 5584,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/1/13/Meadow_in_Zirkow_2021-09-12_20.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meadow_in_Zirkow_2021-09-12_20.jpg",
    "photographer": "Leonhard Lenz",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "A broad grassy opening before a conifer tree line. Tall grass requires wheel occlusion and a modest vehicle scale.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-128220139",
    "name": "Niederfinow Country Field",
    "location": "Niederfinow, Brandenburg, Germany",
    "environment": "meadow",
    "lighting": "daylight",
    "width": 8384,
    "height": 5612,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/c/c2/Meadow_in_Niederfinow_2021-07-17_46.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meadow_in_Niederfinow_2021-07-17_46.jpg",
    "photographer": "Leonhard Lenz",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Wide short-grass field with distant trees and a few far-off buildings. Clear foreground for a broadside vehicle.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-117050410",
    "name": "Basedow Rolling Pasture",
    "location": "Basedow, Mecklenburg-Vorpommern, Germany",
    "environment": "meadow",
    "lighting": "daylight",
    "width": 8368,
    "height": 5584,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Meadow_in_Basedow_2021-09-08_02.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meadow_in_Basedow_2021-09-08_02.jpg",
    "photographer": "Leonhard Lenz",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Open gently rolling green field with wheel tracks leading uphill. Match the terrain angle beneath the tires.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-117050457",
    "name": "Malchin Shaded Field Edge",
    "location": "Malchin, Mecklenburg-Vorpommern, Germany",
    "environment": "meadow",
    "lighting": "daylight",
    "width": 8368,
    "height": 5584,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/d/d3/Meadow_in_Malchin_2021-09-08_01.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meadow_in_Malchin_2021-09-08_01.jpg",
    "photographer": "Leonhard Lenz",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Open meadow viewed from a shaded tree edge. A foreground vehicle should receive the same shade as the lower grass.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-117416590",
    "name": "Zirkow Wide Pasture",
    "location": "Zirkow, Rügen, Germany",
    "environment": "meadow",
    "lighting": "daylight",
    "width": 8368,
    "height": 5584,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Meadow_in_Zirkow_2021-09-12_07.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meadow_in_Zirkow_2021-09-12_07.jpg",
    "photographer": "Leonhard Lenz",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Broad field with a low tree-line horizon and small distant hay bales. Use the lower grassy area and account for its gentle slope.",
    "suitability": "placement",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-122999853",
    "name": "Jacques-Cartier Rocky Shore",
    "location": "Jacques-Cartier National Park, Quebec, Canada",
    "environment": "river",
    "lighting": "daylight",
    "width": 10958,
    "height": 6541,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e8/Jacques-Cartier_National_Park%2C_Quebec%2C_Canada_02.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jacques-Cartier_National_Park,_Quebec,_Canada_02.jpg",
    "photographer": "Wilfredor",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Rocky riverbank at right provides limited land; larger RV placement needs a wider ground plane.",
    "suitability": "scenery",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-183790888",
    "name": "Spanish Peaks Alpine Lake",
    "location": "Custer Gallatin National Forest, Montana, USA",
    "environment": "lake",
    "lighting": "daylight",
    "width": 9573,
    "height": 5238,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Spanish_Peaks%2C_CGNF_%2852258098742%29.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Spanish_Peaks,_CGNF_(52258098742).jpg",
    "photographer": "Jacob W. Frank / NPS",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Spanish_Peaks,_CGNF_(52258098742).jpg",
    "placementNote": "Rocky lakeshore and alpine peaks; use shoreline rocks with careful ground contact.",
    "suitability": "scenery",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-39414227",
    "name": "Yosemite Granite Panorama",
    "location": "Yosemite National Park, California, USA",
    "environment": "mountain",
    "lighting": "storm light",
    "width": 10328,
    "height": 7760,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/3/3a/Yosemite_by_Carol_M._Highsmith.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yosemite_by_Carol_M._Highsmith.jpg",
    "photographer": "Carol M. Highsmith",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Yosemite_by_Carol_M._Highsmith.jpg",
    "placementNote": "Granite valley panorama with wooded foreground; match elevated viewpoint; no broad level parking surface.",
    "suitability": "scenery",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-148251399",
    "name": "Denali Wind-Carved Clouds",
    "location": "Denali National Park and Preserve, Alaska, USA",
    "environment": "mountain",
    "lighting": "daylight",
    "width": 14515,
    "height": 5239,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/0/08/Strong_wind_in_the_Alaska_Range_carves_dramatic_clouds_%282d85b21c-1dd8-b71c-07ef-1eed9ab80987%29.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Strong_wind_in_the_Alaska_Range_carves_dramatic_clouds_(2d85b21c-1dd8-b71c-07ef-1eed9ab80987).jpg",
    "photographer": "Jacob W. Frank",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Strong_wind_in_the_Alaska_Range_carves_dramatic_clouds_(2d85b21c-1dd8-b71c-07ef-1eed9ab80987).jpg",
    "placementNote": "Sweeping Alaska Range panorama with dramatic windswept clouds. Scenic reference: foreground is distant and shadowed, so a new ground plane would be needed.",
    "suitability": "scenery",
    "mime": "image/jpeg"
  },
  {
    "id": "commons-164228988",
    "name": "Castle Valley Sunset",
    "location": "Castle Valley, Utah, USA",
    "environment": "desert",
    "lighting": "golden hour",
    "width": 11648,
    "height": 4874,
    "originalUrl": "https://upload.wikimedia.org/wikipedia/commons/1/16/Fall_Sunset_-_Castle_Valley%2C_Utah%2C_United_States.jpg",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fall_Sunset_-_Castle_Valley,_Utah,_United_States.jpg",
    "photographer": "Romain Guy",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "placementNote": "Dry scrub foreground and distant mesas; use a modest vehicle scale and match low warm side light.",
    "suitability": "scenery",
    "mime": "image/jpeg"
  }
];
export const naturePhotoById = new Map(naturePhotos.map((photo) => [photo.id, photo]));
